### ISSUE TITLE
csgo updated successfully /etc/init.d/csgo-server-launcher: line 265: mail: command not found

### ISSUE THREAD

**Issue by TOWUK** [crazy-max/csgo-server-launcher#100]
#### Steps to reproduce this issue

1. just install script
2. /etc/init.d/csgo-server-launcher create
3. wait

#### Expected Behaviour
![изображение](https://user-images.githubusercontent.com/28830162/133113878-62d53deb-a8cc-480d-88fa-d0de7ff36aa5.png)

**Operating system and platform (ex. Debian 9 64bits)** :
ubuntu latest 20.04

**csgo-server-launcher version (ex. 1.12.3)** : last

### Logs

> Attach these logs to this issue :
> /var/steamcmd/games/csgo/screenlog.*
not have!

> $HOME/Steam/logs/stderr.txt
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize

**Comment by crazy-max** [comment]
```
apt-get install mailutils
```
