### ISSUE TITLE
short workshop problem 

### ISSUE THREAD

**Issue by timotheus0106** [crazy-max/csgo-server-launcher#14]
First of all,

thank you for the great work, it makes hosting much more easy.

so no my question:
i dont wan't to use workshop collections on my server, but i configured it allready.

now when i comment the three lines for setting api_authorization_key, workshop_collection_id etc. out i cannot connect to the server any more. cs go console says: [MM] Sending reservation request to 82.220.39.40:27015

I also tried to leave api_auth_key empty but then the same error displays in console.

So what should i do, to not use any workshop collection or connection between server and that on starting cs go server?

greetings timotheus

**Comment by lucasgautheron** [comment]
I'm having the same issue, have you managed to solve it ? If yes, how ?

**Comment by timotheus0106** [comment]
puh, i don't remember. comment the api_authorization_key, workshop_collection_id out, and try the default configs... then start changing part to part with always trying to connect until it doesn't work anymore... thats what i did.

**Comment by crazy-max** [comment]
@lucasgautheron @timotheus0106 Is this problem still relevant?
