### ISSUE TITLE
Probleme fichier csgo de lancement serveur

### ISSUE THREAD

**Issue by quentingosset** [crazy-max/csgo-server-launcher#15]
Ayant suivis tout le tutoriel suivant : http://www.crazyws.fr/tutos/installer-un-serveur-counter-strike-global-offensive-X4LCM.html

j'ai actuellement mon serveur qui tourne sans soucis.
Mais je rencontre un soucis lorsque je veux mettre votre script car j'obtient l'erreur suivante :+1: 

steam@u12-84524:~$ /etc/init.d/csgo start
bash: /etc/init.d/csgo: /bin/bash^M: bad interpreter: No such file or directory

Ensuite j'ai remarquer que vous demander le : DIR_STEAMCMD="/var/steamcmd"

Personnellement moi je n'ai pas de dossier steamcmd, mon architecture est la suivante :+1: 

--->data
     -->csgo
        --> addons
        --> csgo
              --> bin
              --> cfg
              --> ....
        --> ...
     -->....
     -->steamcmd.sh
     -->....

donc j'ai essayer d'adapté vos url comme ceci : 

DIR_STEAMCMD="/data"
STEAM_LOGIN="anonymous"
STEAM_PASSWORD="anonymous"
STEAM_RUNSCRIPT="$DIR_STEAMCMD/runscript_$SCREEN_NAME"

DIR_ROOT="$DIR_STEAMCMD/csgo"
DIR_GAME="$DIR_ROOT/csgo"
DIR_LOGS="$DIR_GAME/logs"
DAEMON_GAME="srcds_run"

mais j'obtient toujours l'erreur savez vous m'aider ?

Merci :)

**Comment by crazy-max** [comment]
No feedback, i close the ticket

**Comment by fredericrous** [comment]
user is having a dos2unix issue because he is on windoes. ^M in sh script is international I believe.
