### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Gavrilko** [crazy-max/csgo-server-launcher#17]
Hello,

I have problem with this script. I upload script on my VPS and changed chmod on 777. I try start but linux reports error. I use Ubuntu.

Preview: http://pbrd.co/1xOwMIa

My code: http://codepaste.net/v5p5ju

**Comment by crazy-max** [comment]
Code is malformed and does not contains any headers.
Perform this command to retrieve the content properly in your folder where you already have the script :

``wget --no-check-certificate https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.sh``

**Comment by crazy-max** [comment]
Tell me if it solves your problem @Gavrilko
Thanks

**Comment by Gavrilko** [comment]
I have problem with users and console.

root@ubuntu:~# service csgo-server-launcher console
Open console on csgo...
Cannot open your terminal '/dev/pts/0' - please check.
root@ubuntu:~# su steam
steam@ubuntu:/root$ service csgo-server-launcher console
Open console on csgo...
Cannot open your terminal '/dev/pts/0' - please check.
steam@ubuntu:/root$

**Comment by Gavrilko** [comment]
Yeah thanks :) But how to configure script if i want have many servers on my VPS ...

**Comment by crazy-max** [comment]
Create a new issue for this suggestion please.
