### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by DerfOh** [crazy-max/csgo-server-launcher#18]
After editing the conf file I still get an error telling me "No passwd entry for user 'MyScreenName'" when I check the status of the server.

**Comment by DerfOh** [comment]
I changed the values back to 'steam' for USER and 'anonymous' for the STEAM_LOGIN and STEAM_PASSWORD

**Comment by numsu** [comment]
"I changed the values back to 'steam' for USER and 'anonymous' for the STEAM_LOGIN and STEAM_PASSWORD"

Thanks for this! How stupid of me :D
