### ISSUE TITLE
Can't acces Console

### ISSUE THREAD

**Issue by Vosarey** [crazy-max/csgo-server-launcher#19]
Hey,
when the Server is startet with "service csgo-server-launcher start" 
and i try to get into the console with "service csgo-server-launcher console" it always give's me the error
"Cannot open your terminal '/dev/pts/0' - please check." and
"Cannot open your terminal '/dev/pts/3' - please check."

**Comment by DuBtrackz** [comment]
I'm sure that if you had an basic knowledge of linux based distributions, it would be no problem for you...I think this problem is not a bug
You havn't got the permission to access the terminal session.. So change the permission or use script.

**Comment by crazy-max** [comment]
Like @DuBtrackz says it's a permission issue.
Try to log in as linux user used for csgo-server-launcher

**Comment by fuzzy76** [comment]
It's both wrong and rude to call out ownership of terminals as basic knowledge imho. But yes, this is basically just a problem with the way screen works. One way to solve this is to make sure the server runs as the same user as you use for ssh'ing in to the server.

**Comment by lhecker** [comment]
@crazy-max It also does not work if you create a system instead of a regular account... I could solve it by using this though: http://serverfault.com/a/620149

**Comment by pro100it** [comment]
I have the same problem. Solved full by all accounts and login under which you run the launcher. In my case, the Steam user
