### ISSUE TITLE
Intermittent hanging on 'create', when issuing quit command to steamcmd

### ISSUE THREAD

**Issue by Fatbird3** [crazy-max/csgo-server-launcher#21]
When running the create function (./csgo-server-launcher.sh create), the creation hangs when running steamcmd for the first time to update it; specifically it hangs when issuing the quit command or transitioning to the next step. I've tried as both root and the user intended to run the server, to the same effect. I can't quite tell what causes it, as it doesn't happen 100% of the time. This is what it looks like:

```
[----] Update complete, launching Steam...
Redirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Steam>
Steam>
```

It almost seems like the stdin doesn't reach steamcmd or something, but the console becomes non-interactive. Entering 'quit' does nothing; I have to Ctrl+C out of the console.

I tried modifying the script to use '+quit' as opposed to stdin, but had a similar result. No 'Steam>' prompts appeared, but it hung without quitting and required a Ctrl+C break.

I guess this is not a problem specific to csgo-server-launcher, as I can replicate it with SteamCMD itself. I got csgo-server-launcher to work, though, by removing the entire first-time launch for update block, i.e.:

```
  # Run steamcmd for the first time to update it, telling it to quit when it is done
  echo "Updating steamcmd"
  if [ `whoami` = "root" ]
  then
  su - $USER -c "echo quit | $DIR_STEAMCMD/steamcmd.sh"
  else
    echo quit | $DIR_STEAMCMD/steamcmd.sh
  fi
```

SteamCMD updates before it installs CSGO instead.

Not really sure how you want to address this, since it isn't actually a problem with csgo-server-launcher, but it was blocking me from using it. Just thought I'd make you aware.

**Comment by crazy-max** [comment]
I will try to reproduce your problem.
Btw what is your distrib ?

**Comment by Fatbird3** [comment]
This was on Ubuntu 14.04. I'm not sure if you'll be able to reproduce, as it was inconsistent for me. It was also a problem with SteamCMD and not your script. I ended up finding the "updating steamcmd" block to be unnecessary so I removed it and everything worked fine. I haven't run this in a long time, though.

**Comment by crazy-max** [comment]
@Fatbird3 Is this problem still relevant?

**Comment by Fatbird3** [comment]
I haven't run this for years now, so I can't say for sure.

**Comment by crazy-max** [comment]
Ok thanks i close this issue for the moment
