### ISSUE TITLE
usable for multiple servers?

### ISSUE THREAD

**Issue by borli** [crazy-max/csgo-server-launcher#22]
What about making this script usable for multiple csgo servers hosted on 1 server?

**Comment by Raideer** [comment]
I'm interested in this aswell

**Comment by aneeven** [comment]
+1

**Comment by Raideer** [comment]
Figured an easy way to do this.

1. Create a folder ```mkdir ~/server1```
2. ```cd ~/server1```
3. Get the script file ```wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.sh -O csgo-server-launcher --no-check-certificate```
4. Make it executable ```chmod +x csgo-server-launcher```
5. Get the config file ```wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.conf --no-check-certificate```
6. Open the script file with your favourite editor. In my case,
```nano csgo-server-launcher```
7. Edit config file location and save
``` CONFIG_FILE="/home/steam/server1/csgo-server-launcher.conf" ```
8. Edit the main configuration file
9. Run the script (assuming you're in ~/server1)
``` ./csgo-server-launcher start ```

**Comment by borli** [comment]
Please, repeat also the steps for server2 so that both servers would operate simultaneously.

**Comment by mohammadg** [comment]
@borli You can use the above to operate both servers simultaneously. All you are doing is simply having 2 config files and 2 csgo-server-launcher bash files. Make sure the ports are different in the config files and you should be able to run both at the same time.

**Comment by borli** [comment]
OK Thanks. Now it works.

**Comment by crazy-max** [comment]
I will check to implement this feature

**Comment by frohlich** [comment]
This works for totally different servers? Server deathmatch and competitive for example.

**Comment by mohammadg** [comment]
@frohlich Yes.
