### ISSUE TITLE
Solve Permission Issues

### ISSUE THREAD

**Issue by internalsystemerror** [crazy-max/csgo-server-launcher#23]
Ok, so I'm proposing this as a potential improvement as this was the only way I was able to login as one user, to run the script to update the server installed under a different user...

Currently when trying to run the script as a regular user (which differs from the user that installed steamcmd), all sorts of permission issues occur for me on CentOS 7.

The way to solve it was to put the .sh and .conf files both in /etc/csgo-server-launcher, then the /etc/init.d/ script only needs to contain:

`sudo -i -u <username> /etc/csgo-server-launcher/csgo-server-launcher.sh $1`

Then all the if statements to `whoiam` = root can be removed. This may not be the most perfect way, but its all fully tested to work as described with these changes.

**Comment by crazy-max** [comment]
Yes indeed we must check sudoer but not root.
I will improve the script by replacing these statements :

```
if [ `whoami` = root ]
```

with


```
if [ `id -u` -eq 0 ]
```

to check sudoers.

**Comment by crazy-max** [comment]
Solved in 1.13.1
