### ISSUE TITLE
To set this up on a CentOs server I did the following - This is not a bug

### ISSUE THREAD

**Issue by GazCBG** [crazy-max/csgo-server-launcher#24]
Just incase anyone wanting to know how to set this up on a CentOs server.

cd /etc/init.d/

wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.sh -O csgo-server-launcher --no-check-certificate

chmod +x csgo-server-launcher

chkconfig --add csgo-server-launcher

mkdir /etc/csgo-server-launcher/

cd /etc/csgo-server-launcher/

wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.conf -O /etc/csgo-server-launcher/csgo-server-launcher.conf --no-check-certificate

The only changes from normal are:
Line 4 was: update-rc.d csgo-server-launcher defaults
Add Line 6 and moved the last wget to line 7

**Comment by crazy-max** [comment]
I will add an exception for this distrib.
