### ISSUE TITLE
Do not run after reboot

### ISSUE THREAD

**Issue by pro100it** [crazy-max/csgo-server-launcher#28]
Sorry for the bad English, I use translator. (

Installed everything according to instructions, everything starts everything works if run manually. When you reboot you get an error in the boot.log Cannot make directory '/var/run/screen': Permission denied and the server does not start

**Comment by crazy-max** [comment]
Hi,

What is your operating system?

**Comment by pro100it** [comment]
Ubuntu 14.04 x64

**Comment by crazy-max** [comment]
Ubuntu changed the default shell for boot time scripts to dash. Reconfiguring the system back to using bash should resolve it : `dpkg-reconfigure dash` (More info on [this Github issue](https://github.com/msmhq/msm/issues/279))
I strongly advise you to upgrade your server!

**Comment by pro100it** [comment]
Thank you! Now I will try to upgrade my version of 14.04 to the latest updates, go to 16 don't want

**Comment by pro100it** [comment]
Offtop: I had to upgrade Ubuntu to version 16.04 differently did not work (

**Comment by crazy-max** [comment]
`dpkg-reconfigure dash` not working too ?

**Comment by pro100it** [comment]
Yep, in version 14.04 not worked (

**Comment by pro100it** [comment]
Once I updated at 16.04 ksgo-server-launcher  was launched together with the system

**Comment by crazy-max** [comment]
Ok nice then :)
