### ISSUE TITLE
Cant start the Server

### ISSUE THREAD

**Issue by fragstar** [crazy-max/csgo-server-launcher#30]
Hello Guys, 
I have a problem with the command "service csgo-server-launcher start". When i will start the Server with this comment comes: Job for csgo-server-launcher.service failed. See 'systemctl status csgo-server-l    auncher.service' and 'journalctl -xn' for details.

What can i do guys? Can anyone help me?

**Comment by crazy-max** [comment]
What is the output of the command `systemctl status csgo-server-l auncher.service` ?

**Comment by RainDropsGaming** [comment]
steam@(IP):/etc/csgo-server-launcher$ sudo service csgo-server-launcher start

Job for csgo-server-launcher.service failed. See 'systemctl status csgo-server-launcher.service' and 'journalctl -xn' for details.

steam@(IP):/etc/csgo-server-launcher$ systemctl status csgo-server-launcher.service
● csgo-server-launcher.service - LSB: CSGO Server Launcher
   Loaded: loaded (/etc/init.d/csgo-server-launcher)
   Active: failed (Result: exit-code) since Wed 2017-05-03 11:14:18 EDT; 9s ago
  Process: 15117 ExecStart=/etc/init.d/csgo-server-launcher start (code=exited, status=1/FAILURE)

**Comment by crazy-max** [comment]
@RainDropsGaming What is your distrib?

**Comment by RainDropsGaming** [comment]
latest version, And what do you mean distrib?

**Comment by crazy-max** [comment]
@RainDropsGaming Your linux distribution (Debian, Ubuntu, etc...) and version (Debian 8, Ubuntu 17.04, etc...)

**Comment by RainDropsGaming** [comment]
Debian

**Comment by RainDropsGaming** [comment]
After making sure everything was updated, I have the same issue

**Comment by crazy-max** [comment]
Ok can you enter this command `cat /var/steamcmd/games/csgo/screenlog.*` and attach the output as file (drag & drop the file in the textarea)

**Comment by RainDropsGaming** [comment]
cat: /var/steamcmd/games/csgo/screenlog.*: No such file or directory

**Comment by crazy-max** [comment]
Oh this is strange, can you enter this command `/etc/init.d/csgo-server-launcher start` and give me the output ?

**Comment by RainDropsGaming** [comment]
ERROR: You need screen for this script (try apt-get install screen)
I then installed it and now it outputs... 

Starting csgo...
ERROR: ~/Steam/cs_go is not a directory

**Comment by crazy-max** [comment]
Do you read the FAQ : https://github.com/crazy-max/csgo-server-launcher#faq ?
Can you paste your `csgo-server-launcher.conf` please (remove the passwords and gslt token before) ?

**Comment by RainDropsGaming** [comment]
~/Steam is the directory where  I installed SteamCMD
Then CSGO installed to ~/Steam/cs_go (following https://developer.valvesoftware.com/wiki/SteamCMD#Downloading_SteamCMD )


# This file is an integral part of csgo-server-launcher.
# More : https://github.com/crazy-max/csgo-server-launcher#installation

SCREEN_NAME="csgo"
USER="steam"
IP="Removed"
PORT="27015"

# Anonymous connection will be deprecated in the near future. Therefore it is h$
GSLT="Removed" # http://steamcommunity.com/dev/manageg$

DIR_STEAMCMD="~/Steam"
STEAM_LOGIN="anonymous"
STEAM_PASSWORD="anonymous"
STEAM_RUNSCRIPT="$DIR_STEAMCMD/runscript_$SCREEN_NAME"



DIR_ROOT="$DIR_STEAMCMD/cs_go/"
DIR_GAME="$DIR_ROOT/csgo/"
DIR_LOGS="$DIR_STEAMCMD/logs/"
DAEMON_GAME="srcds_run"

UPDATE_LOG="$DIR_LOGS/update_$(date +%Y%m%d).log"
UPDATE_EMAIL=""
UPDATE_RETRY=3

# Workshop : https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_$
API_AUTHORIZATION_KEY="Removed" # http://steamcommunit$
WORKSHOP_COLLECTION_ID="125499818" # http://steamcommunity.com/sharedfiles/file$
WORKSHOP_START_MAP="125488374" # http://steamcommunity.com/sharedfiles/filedeta$

# Game config
MAXPLAYERS="12"
TICKRATE="128"
EXTRAPARAMS="-nohltv +sv_pure 0 +game_type 0 +game_mode 0 +mapgroup mg_bomb +ma$

# Major settings
PARAM_START="-game csgo -console -usercon -secure -autoupdate -steam_dir ${DIR_$
PARAM_UPDATE="+login ${STEAM_LOGIN} ${STEAM_PASSWORD} +force_install_dir ${DIR_$

**Comment by crazy-max** [comment]
I think your server is a fresh install, have you type `service csgo-server-launcher create` before ?

**Comment by RainDropsGaming** [comment]
Creating csgo...
~/Steam does not exist, creating...
ERROR: Could not create ~/Steam

**Comment by crazy-max** [comment]
Ok it's a permission issue like this item in the FAQ : https://github.com/crazy-max/csgo-server-launcher#cannot-create-directory-varsteamcmd

**Comment by crazy-max** [comment]
So for you : `chown -R steam. ~/Steam`
Are you cannected as `root` or `steam` user ?

**Comment by RainDropsGaming** [comment]
My user was named Steam, I switched to root

**Comment by crazy-max** [comment]
hum so you have to change `USER="steam"` to `USER="Steam"` in your config

**Comment by RainDropsGaming** [comment]
ERROR: You must configure the script before you create a server.

I have already configured it though

**Comment by RainDropsGaming** [comment]
Figured it out, I did not set the right IP, After that issue 

Creating csgo...
~/Steam does not exist, creating...
No passwd entry for user 'Steam'
ERROR: Could not create ~/Steam

**Comment by crazy-max** [comment]
You don't have home for your user.
Type `mkdir ~/Steam`

**Comment by crazy-max** [comment]
I suggest to retry from the beginning by following the default csgo-server-launcher steps :

* Connect as `root`
* Read and apply https://github.com/crazy-max/csgo-server-launcher#installation
* useradd -m steam
* mkdir /var/steamcmd
* chown -R steam. /var/steamcmd
* service csgo-server-launcher create
* service csgo-server-launcher start
* service csgo-server-launcher status
* tail -f /var/steamcmd/games/csgo/screenlog.*

**Comment by RainDropsGaming** [comment]
mkdir: cannot create directory ‘/root/Steam’: File exists

**Comment by crazy-max** [comment]
I suggest to retry from the beginning by following the default csgo-server-launcher steps :

* Connect as `root`
* Read and apply https://github.com/crazy-max/csgo-server-launcher#installation
* useradd -m steam
* mkdir /var/steamcmd
* chown -R steam. /var/steamcmd
* service csgo-server-launcher create
* service csgo-server-launcher start
* service csgo-server-launcher status
* tail -f /var/steamcmd/games/csgo/screenlog.*

**Comment by crazy-max** [comment]
@RainDropsGaming is it ok now ?

**Comment by RainDropsGaming** [comment]
I am still working on it now, It is not letting me install steamCMD into /home/steam which is complicating things

**Comment by crazy-max** [comment]
Ok, have you tried with `/var/steamcmd` like i said in my previous comment to figure out if it's a folder issue ?

**Comment by RainDropsGaming** [comment]
Same error in /var/steamcmd

**Comment by RainDropsGaming** [comment]
Another question im having issues with (not related), When I log into the user steam it can only access /home/steam , I have already given it sudo

**Comment by RainDropsGaming** [comment]
After going through an entire re install, It put nothing in /var/steamcmd, Fully empty
thought ~/Steam has everything all steam files and CSGO

# service csgo-server-launcher create
Creating csgo...
~/Steam does not exist, creating...
ERROR: Could not create ~/Steam

**Comment by crazy-max** [comment]
You have to edit your config (DIR_STEAMCMD)

**Comment by RainDropsGaming** [comment]
I have, Did I do something incorrectly?
DIR_STEAMCMD="~/Steam"

DIR_ROOT="$DIR_STEAMCMD/csgo"
DIR_GAME="$DIR_ROOT/csgo"
DIR_LOGS="$DIR_GAME/logs"
DAEMON_GAME="srcds_run"

**Comment by crazy-max** [comment]
`DIR_STEAMCMD="/var/steamcmd"`

**Comment by RainDropsGaming** [comment]
service csgo-server-launcher create
/etc/csgo-server-launcher/csgo-server-launcher.conf: line 38: unexpected EOF while looking for matching `"'
/etc/csgo-server-launcher/csgo-server-launcher.conf: line 39: syntax error: unexpected end of file
Creating csgo...
Downloading steamcmd from http://media.steampowered.com/client/steamcmd_linux.tar.gz
--2017-05-03 17:04:23--  http://media.steampowered.com/client/steamcmd_linux.tar.gz
Resolving media.steampowered.com (media.steampowered.com)... 23.15.4.8, 23.15.4.9
Connecting to media.steampowered.com (media.steampowered.com)|23.15.4.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3170982 (3.0M) [application/octet-stream]
Saving to: ‘steamcmd_linux.tar.gz’

steamcmd_linux.tar. 100%[=====================>]   3.02M  6.22MB/s   in 0.5s

2017-05-03 17:04:23 (6.22 MB/s) - ‘steamcmd_linux.tar.gz’ saved [3170982/3170982]

Extracting and removing the archive
linux32/
linux32/libstdc++.so.6
linux32/steamcmd
steamcmd.sh
steam.sh
Updating steamcmd
Redirecting stderr to '/root/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[  0%] Downloading update (0 of 10,175 KB)...
[  0%] Downloading update (2,470 of 10,175 KB)...
[ 24%] Downloading update (4,740 of 10,175 KB)...
[ 46%] Downloading update (7,089 of 10,175 KB)...
[ 69%] Downloading update (9,227 of 10,175 KB)...
[ 90%] Downloading update (10,175 of 10,175 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
[  0%] Download Complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] !!! Fatal Error: Failed to load libsteam.so

**Comment by RainDropsGaming** [comment]
Any idea what went wrong there?

**Comment by crazy-max** [comment]
You have bad line endings in your config. You have probably edited the file on windows.

**Comment by RainDropsGaming** [comment]
I did, (FTP) How would I fix that then?

**Comment by crazy-max** [comment]
Install dos2unix

**Comment by RainDropsGaming** [comment]
I removed and reinstalled the conf file, Did it all in `nano` and I have the same error

**Comment by crazy-max** [comment]
Have you used wget to dowload the conf?

**Comment by RainDropsGaming** [comment]
Yes

**Comment by RainDropsGaming** [comment]
after reinstalling my OS in general, I followed exactly what each thing said and what you said here 

useradd -m steam
mkdir -p /var/steamcmd
chown -R steam. /var/steamcmd
/etc/init.d/csgo-server-launcher create
/etc/init.d/csgo-server-launcher start
/etc/init.d/csgo-server-launcher status
tail -f /var/steamcmd/games/csgo/screenlog.*

and now it is working great

How do I exit status? CTRL+A+D does not work

**Comment by crazy-max** [comment]
CTRL+A then D
