### ISSUE TITLE
Saveing space, update

### ISSUE THREAD

**Issue by 9611262** [crazy-max/csgo-server-launcher#31]
Hello there @crazy-max 
steamcmd is downloading updates to /steamapps/downloading but my server space is limited (20 GB) and it's not going to happen. Is there a way to delete *.vpk files if update is available? Maybe you can add it to your code as a new option?

Regards and sorry for sending this as an issue (newbie)

**Comment by crazy-max** [comment]
Hi @9611262,

Sure i can implement this option

**Comment by crazy-max** [comment]
Solved in 1.13.1
