### ISSUE TITLE
Start map not changing

### ISSUE THREAD

**Issue by RainDropsGaming** [crazy-max/csgo-server-launcher#36]
...

EXTRAPARAMS="-nohltv +sv_pure 0 +game_type 0 +game_mode 1 +mapgroup mg_bomb +map de_cbble"

PARAM_START="-game csgo -console -usercon -secure -autoupdate -steam_dir ${DIR_STEAMCMD} -steamcmd_script ${STEAM_RUNSCRIPT} -maxplayers_override ${MAXPLAYERS} -tickrate ${TICKRATE} +hostport ${PORT} +ip ${IP} +net_public_adr ${IP} ${EXTRAPARAMS}"

It still launches de_dust2_se

**Comment by crazy-max** [comment]
Sorry i don't bring support for csgo itself.

You can have support here :

* https://forums.alliedmods.net/forumdisplay.php?f=130
* https://steamcommunity.com/app/730/discussions/

But do not forget to read logs in `/var/steamcmd/games/csgo/screenlog.*`

**Comment by RainDropsGaming** [comment]
I felt it was due to your script, With it automatically downloading the workshop maps in the .conf

If I am wrong I can work around it
