### ISSUE TITLE
Server starts but can't connect?

### ISSUE THREAD

**Issue by AchintyaDutta** [crazy-max/csgo-server-launcher#40]
So I start the server and it says "xyz" started successfully
But then I go into the game and enter in connect <IP>:<Port> and it keeps retrying?

What can I do? I tested this on other Steam accounts as well. I didn't do an anonymous login.
![image](https://user-images.githubusercontent.com/20384214/33309729-273782d0-d445-11e7-902d-993d7b5d8c30.png)

I'm sorry if I've made a silly mistake or something, I'm very new to this. 

Thank you!

**Comment by shikharbhardwaj** [comment]
Check your firewall settings (port 27015 should be open).
