### ISSUE TITLE
Docker version problem.

### ISSUE THREAD

**Issue by MikkelDK** [crazy-max/csgo-server-launcher#45]
#### Steps to reproduce this issue

1. Trying docker-compose up from the docker folder.
2. Getting an error about the compose file is only works for 2.0 and not 3.2

#### Expected Behaviour
Did trying to use your docker version of csgo-server-launcher.
I did use docker-compose up, but getting an error with the compose file is only for 2.0 and not 3.2.

#### Actual Behaviour
Same as noted ^^

### Configuration

**Operating system and platform (ex. Debian 9 64bits)** : Debian 9 64bits

**csgo-server-launcher version (ex. 1.12.3)** : 1.13.2

### Logs
Just an error: 

> Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key or omit the `version` key and place your service definitions at the root of the file to use version 1.

### Screenshots
![](https://i.gyazo.com/67c7c9e56d9cdaafb1a01181d1554bef.png)

**Comment by crazy-max** [comment]
Can you give me the output of `docker info` and `docker-compose --version`
Also take a look here for compatibility : https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix

**Comment by MikkelDK** [comment]
## Docker info:
```
root@B-F5-20:~/server# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.16.18-rt12-tjaarda-powered
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.39GiB
Name: B-F5-20
ID: EUL5:XXIM:FCCC:DOWL:LM5B:AJWD:QUSP:2WQO:YFT2:7UNS:V2QS:AB6P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

## docker-compose version
```
docker-compose version 1.8.0, build unknown
```

**Comment by MikkelDK** [comment]
//Fixed. seems docker's APT don't update to the newest! ;) I got it fixed! :D
