### ISSUE TITLE
Server will not start if extra params are added

### ISSUE THREAD

**Issue by jintzy** [crazy-max/csgo-server-launcher#47]
When I try to start my server it fails after saying it was done successfully if i add extra params. When I don't, it works fine. This wouldn't be a problem because I can just type them in console after I start the server, but every time the map changes all the params reset to default, with the exclusion of hostname. Mostly I want to have mp_teammates_are_enemies set to 1, but there are a few other's I would like to add as well but am unable to. I was poking around to see if I could just throw them in the config file that runs every time the map is changed, but was unable to find such a file. Also, people are only able to connect by typing the IP followed by the port, by adding it to their favorites, or under the LAN tab, which doesn't really matter because only I can do that anyway because it's on my network. Also, the server doesn't show up in the community server browser other than the LAN tab. This is probably something on my end, but any help would be appreciated there.

**Comment by crazy-max** [comment]
You can add your param through [EXTRA_PARAMS](https://github.com/crazy-max/csgo-server-launcher/wiki/Configuration#extraparams) var in your config file.
