### ISSUE TITLE
HTTP Error downloading

### ISSUE THREAD

**Issue by mspencerl87** [crazy-max/csgo-server-launcher#49]
### Behaviour

Error: An HTTP Request took too longer to complete

#### Steps to reproduce this issue

1. docker-compose up -d
2. docker-compose logs -f
3. error after connecting to steam

#### Expected Behaviour

> Downloads CSGO

#### Actual Behaviour

> Failure to connect

### Configuration

Ubuntu 16.04

Latest Pull/ Default config except for GSLT and API key

### Logs

> Attach these logs to this issue :
> /var/steamcmd/games/csgo/screenlog.*
> $HOME/Steam/logs/stderr.txt

### Screenshots

> Sometimes screenshots are better ;)
![2019_06_14_13_02_24_LNHOST](https://user-images.githubusercontent.com/47121646/59528835-f2c09980-8ea4-11e9-8d6b-d296976572ce.png)

**Comment by crazy-max** [comment]
Not linked to csgo-server-laucnher but docker-compose.
Post an issue on [docker/compose](https://github.com/docker/compose). Also docker/compose#3633 and docker/compose#5620 might help.
