### ISSUE TITLE
lib32ncurses5-dev must be used on 19.04

### ISSUE THREAD

**Issue by dEROZA** [crazy-max/csgo-server-launcher#50]
lib32ncurses5 not exist in disco reps, instead lib32ncurses5-dev must be used for 19.04 release. And why u use /var/ dir? Some people can mount var with small disc space))

**Comment by crazy-max** [comment]
@dEROZA

You are not on a [LTS release of Ubuntu](https://packages.ubuntu.com/search?keywords=lib32ncurses5) so that's pretty normal.
