### ISSUE TITLE
Composer closed, but docker still works in background.

### ISSUE THREAD

**Issue by dEROZA** [crazy-max/csgo-server-launcher#51]
![composer_closed_docker_works](https://user-images.githubusercontent.com/8126176/60852383-1966bb80-a22a-11e9-946e-733d7420a124.png)

I'm a newbie in docker, so it's a big deal for me. I use composer installer as you told, but in my var dir isn't enought space for csgo server location. Therefore steamcmd can't install it, and I don't understand how I can finish containers' looped operation. And how I can change srcds location, in place of /var/? thx

**Comment by dEROZA** [comment]
I tried to use stop command on docker, and create a symlink to other localtion from /var/.../csgo

**Comment by crazy-max** [comment]
If you are new to Docker, you need to understand its operating philosophy before making "bad things". I suggest to read their [Get started guide](https://docs.docker.com/get-started/). And next read the [Docker compose guide](https://docs.docker.com/compose/gettingstarted/). This should help you getting started. As your problem concerns volumes under Docker, read [this](Concerning https://docs.docker.com/storage/volumes/) too. You can also find help on [this subreddit](https://www.reddit.com/r/docker).
