### ISSUE TITLE
Where SRCDS console?

### ISSUE THREAD

**Issue by dEROZA** [crazy-max/csgo-server-launcher#52]
how to grab srcds console when running with docker?

**Comment by crazy-max** [comment]
It's explained on [Usage page](https://github.com/crazy-max/csgo-server-launcher/wiki/Usage) (console arg).

**Comment by dEROZA** [comment]
> 
> 
> It's explained on [Usage page](https://github.com/crazy-max/csgo-server-launcher/wiki/Usage) (console arg).

in docker-composer? Console command not exists!

**Comment by dEROZA** [comment]
omg, i thought that docker +composer and them enought for server management.

**Comment by dEROZA** [comment]
why you EXPOSE 27015 27015/udp only, what about MasterServer 26900-2690x?

**Comment by dEROZA** [comment]
and why steam user has sudo-nopassword prev?

**Comment by dEROZA** [comment]
why you "EXPOSE 27015 27015/udp" only, what about MasterServer 26900-2690x?
and why steam user has sudo-nopassword prev?

can u tell me, where csgo launcher will install the server, update and install new packages, launchers' services? Is them on ghost VM or in docker container will be placed?

**Comment by crazy-max** [comment]
I think you have a misunderstanding about how Docker works. See [my comment](https://github.com/crazy-max/csgo-server-launcher/issues/51#issuecomment-509832531). And please one issue at a time.

**Comment by mgerb** [comment]
It's still unclear how to access the console while running with docker. I run it with the -console and am still unsure how to get console access while it's running. I'm pretty familiar with docker, so maybe I'm just missing something here?

**Comment by crazy-max** [comment]
@mgerb The console is currently not available for the Docker image.

**Comment by webman** [comment]
@crazy-max have some idea how to use console? Or just send commands to srcds?
