### ISSUE TITLE
Environment variables in docker-composer has bug

### ISSUE THREAD

**Issue by dEROZA** [crazy-max/csgo-server-launcher#53]
```
Environment variables
    TZ : The timezone assigned to the container (default UTC)
    PUID : The timezone assigned to the container (default 1000)
    PGID : The timezone assigned to the container (default 1000)
```
PUID, PGID  not works for 
> docker-composer up -d
I've already another user under 1000 id, steam at 1001.

I configured _csgo-server-launcher.env_, and change _PUID_, and _PGID_ to _1001_, but instead of this docker installed files as 1000 uid forcibly

**Comment by crazy-max** [comment]
What's the content of your compose file ?

**Comment by dEROZA** [comment]
```
TZ=Asia/Irkutsk
PUID=1001
PGID=1001
SSMTP_HOST=smtp.example.com
SSMTP_PORT=587
SSMTP_HOSTNAME=example.com
SSMTP_USER=smtp@example.com
SSMTP_PASSWORD=
SSMTP_TLS=YES

GSLT=
STEAM_LOGIN=anonymous
STEAM_PASSWORD=anonymous
UPDATE_EMAIL=
UPDATE_RETRY=3
CLEAR_DOWNLOAD_CACHE=0
API_AUTHORIZATION_KEY=
WORKSHOP_COLLECTION_ID=125499818
WORKSHOP_START_MAP=125488374
MAXPLAYERS=32
TICKRATE=128
EXTRAPARAMS=-nohltv +sv_pure 0 +game_type 0 +game_mode 0 +mapgroup mg_active +map de_dust2
```

**Comment by dEROZA** [comment]
> 
> 
> What's the content of your compose file ?

```
TZ=Asia/Irkutsk
PUID=1001
PGID=1001
SSMTP_HOST=smtp.example.com
SSMTP_PORT=587
SSMTP_HOSTNAME=example.com
SSMTP_USER=smtp@example.com
SSMTP_PASSWORD=
SSMTP_TLS=YES

GSLT=
STEAM_LOGIN=anonymous
STEAM_PASSWORD=anonymous
UPDATE_EMAIL=
UPDATE_RETRY=3
CLEAR_DOWNLOAD_CACHE=0
API_AUTHORIZATION_KEY=
WORKSHOP_COLLECTION_ID=125499818
WORKSHOP_START_MAP=125488374
MAXPLAYERS=32
TICKRATE=128
EXTRAPARAMS=-nohltv +sv_pure 0 +game_type 0 +game_mode 0 +mapgroup mg_active +map de_dust2
```

**Comment by crazy-max** [comment]
Compose file..

**Comment by dEROZA** [comment]
> 
> 
> Compose YML file..

what is it mean?)

**Comment by crazy-max** [comment]
> what is it mean?)

I talk about `docker-compose.yml`.

> Where docker file will be executed, on host or in container?

In a container. Please read [my comment](https://github.com/crazy-max/csgo-server-launcher/issues/51#issuecomment-509832531) to fully understand how docker works.

> I've a trouble with /var/, it has a very small disc space.

Like I said in the [README](https://github.com/crazy-max/csgo-server-launcher/tree/master/docker#docker-compose), the path `/var/csgo-server-launcher/` on your host is an example. Use another path if you want.
