### ISSUE TITLE
Is it correct description for these PUID and  PGID?

### ISSUE THREAD

**Issue by dEROZA** [crazy-max/csgo-server-launcher#54]
https://github.com/crazy-max/csgo-server-launcher/tree/master/docker
```
PUID : The timezone assigned to the container (default 1000)
PGID : The timezone assigned to the container (default 1000)
```

P.S. why server uses old 1000 value forcibly when I changed PUID and PGID to another value?
> csgo-updater | groupmod: Permission denied.
> csgo-updater | groupmod: cannot lock /etc/group; try again later.

I think you not fully understand what're doing.. are you an author of this script? Or steam user it's a steamcmd maintenance user only, and srcds can be running under another user? Or what? Tell me ^_^

**Comment by KenMurphy** [comment]
dude just stop
