### ISSUE TITLE
Cant set DNS

### ISSUE THREAD

**Issue by St0ner1995** [crazy-max/csgo-server-launcher#55]
Is it possible to have an environment variable somewhere to set the DNS server so i can use a steam cache?

Thanks

**Comment by crazy-max** [comment]
Hi @St0ner1995, is it about the docker image?

**Comment by St0ner1995** [comment]
Yes it is

**Comment by crazy-max** [comment]
@St0ner1995 You can define custom dns server using `--dns` switch with [`docker run` command](https://docs.docker.com/engine/reference/run/#network-settings). If you're using docker-compose, take a look [here](https://docs.docker.com/compose/compose-file/#dns).
