### ISSUE TITLE
Can't get docker image running docker-compose

### ISSUE THREAD

**Issue by J0nathan-S** [crazy-max/csgo-server-launcher#56]
#### Steps to reproduce this issue

1. Download the three files from git repo: [docker-compose-examples](https://github.com/crazy-max/csgo-server-launcher/tree/master/docker/examples/compose)
2. Clone GitHub Repo
3. Install Server in order to have Steam, CSGO and SteamCMD installed correctly and working
4. docker-compose up -d
5. docker-compose logs -f

#### Expected Behaviour

> The CSGO-Server should start

#### Actual Behaviour

> On "docker-compose up -d" The Server logs say that Steamcmd needs to be online to update. When Installing and starting the csgo-server-launcher without docker-compose, it works like a charm...

### Configuration

**Operating system and platform (ex. Debian 9 64bits)** : Ubuntu 18.04 64 bit

**csgo-server-launcher version (ex. 1.12.3)** : latest

[csgo-server-launcher.env.txt](https://github.com/crazy-max/csgo-server-launcher/files/3592260/csgo-server-launcher.env.txt)
[docker-compose.yml.txt](https://github.com/crazy-max/csgo-server-launcher/files/3592261/docker-compose.yml.txt)
YES, I did check the GSLT as well as the API_AUTHORIZATION_KEY twice.

### Logs
[docker log.txt](https://github.com/crazy-max/csgo-server-launcher/files/3592247/docker.log.txt)
[screenlog.0.txt](https://github.com/crazy-max/csgo-server-launcher/files/3592248/screenlog.0.txt)
[stderr.txt](https://github.com/crazy-max/csgo-server-launcher/files/3592249/stderr.txt)

### Screenshots

> Sometimes screenshots are better ;)

**Comment by crazy-max** [comment]
Hi @J0nathan-S, thanks for your report. Can you test with this image: `crazymax/csgo-server-launcher:1.13.4`?

**Comment by J0nathan-S** [comment]
> 
> 
> Hi @J0nathan-S, thanks for your report. Can you test with this image: `crazymax/csgo-server-launcher:1.13.4`?

Didn't help. Same behaviour.

**Comment by J0nathan-S** [comment]
Okay, the problem is on my side. Somehow no docker Image is able to reach the internet.
