### ISSUE TITLE
Regular password, RCON password setup, steam login necessity

### ISSUE THREAD

**Issue by Gugols** [crazy-max/csgo-server-launcher#57]
Hi, I have two questions regarding this setup:

- How can I specify RCON (administration) password to be used?
- How can I protect my server and require a password in order to play in it?
- Why there's a need to specify my Steam's user & password in config?

**Comment by melashkov** [comment]
> Hi, I have two questions regarding this setup:
> 
> * How can I specify RCON (administration) password to be used?
> * How can I protect my server and require a password in order to play in it?
> * Why there's a need to specify my Steam's user & password in config?

> Create file /var/steamcmd/games/csgo/csgo/cfg/autoexec.cfg
`
hostname "My CS:GO Dedicated Server"
rcon_password "stayhome_savelifes"
sv_password "stayhome" //Only set this if you intend to have a private server!
sv_cheats 0 //This should always be set, so you know it's not on
`

please see https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers

**Comment by crazy-max** [comment]
@Gugols 

> Why there's a need to specify my Steam's user & password in config?

Not required but advised in some cases when updates could not be downloaded. Also, for security reasons it is recommended that you create a new Steam account just for your dedicated servers.
