### ISSUE TITLE
How to run commands via one-liner SSH and get output?

### ISSUE THREAD

**Issue by HTMHell** [crazy-max/csgo-server-launcher#59]
I have a `NodeJS` script that connects to the server via SSH.
I want to run commands at `/etc/init.d/csgo-server-launcher console` in that SSH connection.
I managed to do so by running the following command:
`export TERM=screen && echo "command" | /etc/init.d/csgo-server-launcher console`
The only issue is, I don't get an output, because the `console` is still hanging there.

I want to run the command `host_map` and get the output. Is it possible?

I think that if I close the `csgo-server-launcher console` terminal it will fix that issue. Is it possible to that? (like `exit` in MySQL)

**Comment by crazy-max** [comment]
This is not currently supported. Feel free to open a PR to fix that. Thanks.
