### ISSUE TITLE
Update needed ?

### ISSUE THREAD

**Issue by Dowoh** [crazy-max/csgo-server-launcher#60]
When  i go for automatic install via the scripte, i got that error 

```
Starting CSGO Server Launcher install (v1.13.5)...

Adding i386 architecture...
Installing required packages...
ls
E: Unable to locate package lib32ncurses5
ERROR: Cannot install required packages...
```

Found out that if i change that line of code in the manual install

`apt-get install -y -q libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 curl gdb screen tar wget`

into 

`apt-get install -y -q libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses6 lib32z1 curl gdb screen tar wget`

The install goes well.

Hope it will work

Dowo

**Comment by crazy-max** [comment]
@Dowoh That's true if you are on debian buster. Are you? Please create a proper [bug report](https://github.com/crazy-max/csgo-server-launcher/issues/new?template=bug_report.md) next time, It'll save me the guessing ;)

**Comment by shmidtelson** [comment]
Ubuntu 18.04.2 LTS not found package lib32ncurses6
Fix:
https://packages.ubuntu.com/cosmic/amd64/lib32ncurses6/download

**Comment by melashkov** [comment]
can you please elaborate on that?
`
Error
two or more packages specified (lib32ncurses6 cosmic)
`
not sure what it is mean?
