### ISSUE TITLE
How to open server on other port ?

### ISSUE THREAD

**Issue by shmidtelson** [crazy-max/csgo-server-launcher#61]
Statically use 27015.
I am use two servers on one vds. How to use 27016 port?

**Comment by crazy-max** [comment]
See [Configuratino doc](https://github.com/crazy-max/csgo-server-launcher/blob/master/doc/configuration.md).

**Comment by shmidtelson** [comment]
@crazy-max Sorry. I am use a Docker. And in container port statically use.

**Comment by crazy-max** [comment]
* https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose
* https://docs.docker.com/config/containers/container-networking/
* https://docs.docker.com/compose/compose-file/#ports

**Comment by crazy-max** [comment]
@shmidtelson In your case `-p 27016:27015 -p 27016:27015/udp`

**Comment by shmidtelson** [comment]
@crazy-max Ok, look.
Docker-compose:
![Screenshot_20191021_192344](https://user-images.githubusercontent.com/6944443/67225271-9a456e00-f43b-11e9-8344-336bef7f6f46.png)
Start command inside docker-compose:
![Screenshot_20191021_192652](https://user-images.githubusercontent.com/6944443/67225337-b77a3c80-f43b-11e9-9a9a-c105208953df.png)
Result in search...
![ezgif-4-52a7d4cfa7c6](https://user-images.githubusercontent.com/6944443/67225524-16d84c80-f43c-11e9-875d-3fcdf56aa794.gif)

**Comment by crazy-max** [comment]
@shmidtelson Hum maybe because the server is registered on 27015 internally. Keep you in touch.

**Comment by shmidtelson** [comment]
@crazy-max I think, param **+hostport** send info in global search.
I have one idea:
Add in **.env** file param **PORT** with def. value 27015, and use this param in
docker-compose.yml
```
ports:
      - target: ${PORT}
        published: ${PORT}
        protocol: udp
      - target: ${PORT}
        published: ${PORT}
        protocol: tcp
```
And in srcds params **+hostport** ${PORT} in install script

**Comment by crazy-max** [comment]
Yes that's it

**Comment by crazy-max** [comment]
I prepare a PR keep u in touch

**Comment by crazy-max** [comment]
@shmidtelson Should be ok now
