### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by kuper1994** [crazy-max/csgo-server-launcher#66]
There is any option to start 5 servers from same command 
Mean if I'm starting first server it will start with 27015 port, 2nd will start with 27016, 3rd 27017 and etc.

thanks.

**Comment by crazy-max** [comment]
@kuper1994 No you have to create each instance manually. For more info see https://github.com/crazy-max/csgo-server-launcher/blob/master/doc/faq.md#create-multiple-instances
